// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendUnixDateRequest struct {
	Field     string          `queryParam:"style=form,explode=true,name=field"`
	SetToNull bool            `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet     bool            `queryParam:"style=form,explode=true,name=unSet"`
	Unixdate  shared.Unixdate `request:"mediaType=application/json"`
}

func (o *SendUnixDateRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendUnixDateRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendUnixDateRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

func (o *SendUnixDateRequest) GetUnixdate() shared.Unixdate {
	if o == nil {
		return shared.Unixdate{}
	}
	return o.Unixdate
}

type SendUnixDateResponse struct {
	ContentType    string
	ServerResponse *shared.ServerResponse
	StatusCode     int
	RawResponse    *http.Response
}

func (o *SendUnixDateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendUnixDateResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendUnixDateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendUnixDateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
