// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendChildRequest struct {
	ChildClass shared.ChildClass `request:"mediaType=application/json"`
	Field      string            `queryParam:"style=form,explode=true,name=field"`
	SetToNull  bool              `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet      bool              `queryParam:"style=form,explode=true,name=unSet"`
}

func (o *SendChildRequest) GetChildClass() shared.ChildClass {
	if o == nil {
		return shared.ChildClass{}
	}
	return o.ChildClass
}

func (o *SendChildRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendChildRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendChildRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

type SendChildResponse struct {
	// HTTP response content type for this operation
	ContentType    string
	ServerResponse *shared.ServerResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SendChildResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendChildResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendChildResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendChildResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
