// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendRfc1123DateMapRequest struct {
	Rfc1123datemap shared.Rfc1123datemap `request:"mediaType=application/json"`
	Field          string                `queryParam:"style=form,explode=true,name=field"`
	SetToNull      bool                  `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet          bool                  `queryParam:"style=form,explode=true,name=unSet"`
}

func (o *SendRfc1123DateMapRequest) GetRfc1123datemap() shared.Rfc1123datemap {
	if o == nil {
		return shared.Rfc1123datemap{}
	}
	return o.Rfc1123datemap
}

func (o *SendRfc1123DateMapRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendRfc1123DateMapRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendRfc1123DateMapRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

type SendRfc1123DateMapResponse struct {
	ContentType    string
	ServerResponse *shared.ServerResponse
	StatusCode     int
	RawResponse    *http.Response
}

func (o *SendRfc1123DateMapResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendRfc1123DateMapResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendRfc1123DateMapResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendRfc1123DateMapResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
