// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendRfc1123DateArrayRequest struct {
	Rfc1123datearray shared.Rfc1123datearray `request:"mediaType=application/json"`
	Field            string                  `queryParam:"style=form,explode=true,name=field"`
	SetToNull        bool                    `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet            bool                    `queryParam:"style=form,explode=true,name=unSet"`
}

func (o *SendRfc1123DateArrayRequest) GetRfc1123datearray() shared.Rfc1123datearray {
	if o == nil {
		return shared.Rfc1123datearray{}
	}
	return o.Rfc1123datearray
}

func (o *SendRfc1123DateArrayRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendRfc1123DateArrayRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendRfc1123DateArrayRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

type SendRfc1123DateArrayResponse struct {
	ContentType    string
	ServerResponse *shared.ServerResponse
	StatusCode     int
	RawResponse    *http.Response
}

func (o *SendRfc1123DateArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendRfc1123DateArrayResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendRfc1123DateArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendRfc1123DateArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
