// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendRfc1123DateRequest struct {
	Rfc1123date shared.Rfc1123date `request:"mediaType=application/json"`
	Field       string             `queryParam:"style=form,explode=true,name=field"`
	SetToNull   bool               `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet       bool               `queryParam:"style=form,explode=true,name=unSet"`
}

func (o *SendRfc1123DateRequest) GetRfc1123date() shared.Rfc1123date {
	if o == nil {
		return shared.Rfc1123date{}
	}
	return o.Rfc1123date
}

func (o *SendRfc1123DateRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendRfc1123DateRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendRfc1123DateRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

type SendRfc1123DateResponse struct {
	// HTTP response content type for this operation
	ContentType    string
	ServerResponse *shared.ServerResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SendRfc1123DateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendRfc1123DateResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendRfc1123DateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendRfc1123DateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
