// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/models/shared"
	"net/http"
)

type SendUnixDateArrayRequest struct {
	Field         string               `queryParam:"style=form,explode=true,name=field"`
	SetToNull     bool                 `queryParam:"style=form,explode=true,name=setToNull"`
	UnSet         bool                 `queryParam:"style=form,explode=true,name=unSet"`
	Unixdatearray shared.Unixdatearray `request:"mediaType=application/json"`
}

func (o *SendUnixDateArrayRequest) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *SendUnixDateArrayRequest) GetSetToNull() bool {
	if o == nil {
		return false
	}
	return o.SetToNull
}

func (o *SendUnixDateArrayRequest) GetUnSet() bool {
	if o == nil {
		return false
	}
	return o.UnSet
}

func (o *SendUnixDateArrayRequest) GetUnixdatearray() shared.Unixdatearray {
	if o == nil {
		return shared.Unixdatearray{}
	}
	return o.Unixdatearray
}

type SendUnixDateArrayResponse struct {
	ContentType    string
	ServerResponse *shared.ServerResponse
	StatusCode     int
	RawResponse    *http.Response
}

func (o *SendUnixDateArrayResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendUnixDateArrayResponse) GetServerResponse() *shared.ServerResponse {
	if o == nil {
		return nil
	}
	return o.ServerResponse
}

func (o *SendUnixDateArrayResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendUnixDateArrayResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
