// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Rfc1123date struct {
	DateTime  *string `json:"dateTime,omitempty"`
	DateTime1 string  `json:"dateTime1"`
}

func (o *Rfc1123date) GetDateTime() *string {
	if o == nil {
		return nil
	}
	return o.DateTime
}

func (o *Rfc1123date) GetDateTime1() string {
	if o == nil {
		return ""
	}
	return o.DateTime1
}
