// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ServerResponseInput struct {
}

type ServerResponse struct {
	Message *string                        `json:"Message,omitempty"`
	Input   map[string]ServerResponseInput `json:"input,omitempty"`
	Passed  bool                           `json:"passed"`
}

func (o *ServerResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *ServerResponse) GetInput() map[string]ServerResponseInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *ServerResponse) GetPassed() bool {
	if o == nil {
		return false
	}
	return o.Passed
}
