// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/optional-v1-go/pkg/types"
	"github.com/speakeasy-sdks/optional-v1-go/pkg/utils"
)

type Simpledatearray struct {
	Date  []types.Date `json:"date,omitempty"`
	Date1 []types.Date `json:"date1,omitempty"`
}

func (s Simpledatearray) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Simpledatearray) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Simpledatearray) GetDate() []types.Date {
	if o == nil {
		return nil
	}
	return o.Date
}

func (o *Simpledatearray) GetDate1() []types.Date {
	if o == nil {
		return nil
	}
	return o.Date1
}
