// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Unixdatemap struct {
	DateTime  map[string]float64 `json:"dateTime,omitempty"`
	DateTime1 map[string]float64 `json:"dateTime1"`
}

func (o *Unixdatemap) GetDateTime() map[string]float64 {
	if o == nil {
		return nil
	}
	return o.DateTime
}

func (o *Unixdatemap) GetDateTime1() map[string]float64 {
	if o == nil {
		return map[string]float64{}
	}
	return o.DateTime1
}
