// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Unixdatearray struct {
	DateTime  []float64 `json:"dateTime,omitempty"`
	DateTime1 []float64 `json:"dateTime1"`
}

func (o *Unixdatearray) GetDateTime() []float64 {
	if o == nil {
		return nil
	}
	return o.DateTime
}

func (o *Unixdatearray) GetDateTime1() []float64 {
	if o == nil {
		return []float64{}
	}
	return o.DateTime1
}
