// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Unixdate struct {
	DateTime  *float64 `json:"dateTime,omitempty"`
	DateTime1 float64  `json:"dateTime1"`
}

func (o *Unixdate) GetDateTime() *float64 {
	if o == nil {
		return nil
	}
	return o.DateTime
}

func (o *Unixdate) GetDateTime1() float64 {
	if o == nil {
		return 0.0
	}
	return o.DateTime1
}
